[start]
cmd = "poetry run app"

[variables]
PYTHONUNBUFFERED = "1"  # Ensures Python output is sent straight to the terminal without buffering
FLASK_ENV = "production"  # Runs the Flask server in production mode
